swiftmailer:
    url: '%env(MAILER_URL)%'
    spool:
        type: file
        path: '%kernel.project_dir%/var/spool'
    stream-options:
        ssl:
            allow_self_signed : true
            verify_peer: false
            verify_peer_name: false
